const EValue = {

    CERO:{
        name:"CERO",
        score:0
    },
    ONE:{
        name:"ONE",
        score:1    
    },
    TWO:{
        name:"TWO",
        score:2    
    },
    THREE:{
        name:"THREE",
        score:3    
    },
    FOUR:{
        name:"FOUR",
        score:4    
    },
    FIVE:{
        name:"FIVE",
        score:5    
    },
    SIX:{
        name:"SIX",
        score:6    
    },
    SEVEN:{
        name:"SEVEN",
        score:7    
    },
    EIGHT:{
        name:"EIGHT",
        score:8    
    },
    NINE:{
        name:"NINE",
        score:9    
    },
    DTWO:{
        name:"DTWO",
        score:20    
    },
    REVERSE:{
        name:"REVERSE",
        score:20    
    },
    SKIP:{
        name:"SKIP",
        score:20    
    },
    WILD:{
        name:"WILD",
        score:50   
    },
    DFOUR:{
        name:"DFOUR",
        score:50   
    }
};
Object.freeze(EValue);